# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
  - job:
    displayName: Send to docker Registry
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'docker images'
      
  - job:
    displayName: Run script
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath'
        scriptPath: 'w3resource_python-exercises/python_basic_1/ex1.py'
