trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          bash -c "
          echo 'DOCKER BUILD'
          docker build -t robertm131/trainingpythonscripts .
          echo 'DOCKER IMAGES'
          docker images
          echo 'DOCKER PUSH'
          docker login --username=$(DOCKER_REG_LOGIN) --password=$(DOCKER_REG_PASSWORD)
          /usr/bin/docker push robertm131/trainingpythonscripts
          echo '----------------------------------HERE END'
          "

- stage: Run
  displayName: Run script from repository
  jobs:   
  - job:
    displayName: Run script
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          bash -c "
          docker login --username=$(DOCKER_REG_LOGIN) --password=$(DOCKER_REG_PASSWORD)
          docker pull robertm131/trainingpythonscripts
          "
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          bash -c "
          docker run -ti robertm131/trainingpythonscripts /bin/bash 
          "

